spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 52.66.150.21:9092
      bindings:
        greetings-in:
          destination: greetings
          contentType: application/json
        greetings-out:
          destination: greetings
          contentType: application/json
